# Generated by Django 4.2.20 on 2025-05-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=128, unique=True, verbose_name='权限别名')),
                ('desc', models.CharField(blank=True, max_length=128, verbose_name='权限描述')),
                ('menu', models.CharField(blank=True, max_length=32, null=True, verbose_name='关联菜单')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='角色名称')),
                ('permissions', models.ManyToManyField(blank=True, to='rbac.permission', verbose_name='权限集合')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
            },
        ),
    ]
